Bayes' Theorem in Medical Diagnosis
Bayes' Theorem can be applied to medical diagnosis to determine the probability of a patient having a disease given a positive test result.

Bayes' Theorem Formula:

𝑃
(
𝐴
∣
𝐵
)
=
𝑃
(
𝐵
∣
𝐴
)
⋅
𝑃
(
𝐴
)
𝑃
(
𝐵
)
P(A∣B)= 
P(B)
P(B∣A)⋅P(A)
​
 

Where:

𝑃
(
𝐴
∣
𝐵
)
P(A∣B) is the posterior probability (probability of having the disease given a positive test).
𝑃
(
𝐵
∣
𝐴
)
P(B∣A) is the likelihood (probability of testing positive if the patient has the disease).
𝑃
(
𝐴
)
P(A) is the prior probability (initial probability of having the disease).
𝑃
(
𝐵
)
P(B) is the marginal likelihood (probability of testing positive, regardless of disease status).

Let's assume:

The probability of having the disease (
𝑃
(
𝐷
)
P(D)) is 1% (0.01).
The probability of testing positive given the disease (
𝑃
(
𝑇
∣
𝐷
)
P(T∣D)) is 99% (0.99).
The probability of testing positive without the disease (
𝑃
(
𝑇
∣
¬
𝐷
)
P(T∣¬D)) is 5% (0.05).
Using Bayes' Theorem, we can calculate the probability of having the disease given a positive test result (
𝑃
(
𝐷
∣
𝑇
)
P(D∣T)).

In [1]:
# Given probabilities
P_D = 0.01            # Prior probability of having the disease
P_not_D = 1 - P_D     # Prior probability of not having the disease
P_T_given_D = 0.99    # Probability of testing positive given having the disease
P_T_given_not_D = 0.05 # Probability of testing positive given not having the disease

# Applying Bayes' Theorem
P_T = P_T_given_D * P_D + P_T_given_not_D * P_not_D  # Total probability of testing positive
P_D_given_T = (P_T_given_D * P_D) / P_T  # Posterior probability of having the disease given a positive test

print(f"The probability of having the disease given a positive test result is: {P_D_given_T:.4f}")


The probability of having the disease given a positive test result is: 0.1667


## Eigenvalues and Eigenvectors
Eigenvalues and eigenvectors are key concepts in linear algebra, used in many applications like PCA, stability analysis, and quantum mechanics.

Example:

Given a 2x2 matrix:
𝐴
=
[
4
1
2
3
]
A=[ 
4
2
​
  
1
3
​
 ]

We can find its eigenvalues and corresponding eigenvectors.

In [2]:
import numpy as np

# Define the matrix
A = np.array([[4, 1],
              [2, 3]])

# Compute the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)


Eigenvalues:
[5. 2.]

Eigenvectors:
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


### Determinant and Inverse of a 3x3 Matrix

In [5]:
import numpy as np

# Define the 3x3 matrix
B = np.array([[2, 3, 1],
              [4, 1, -3],
              [2, 5, 3]])

# Calculate the determinant
determinant = np.linalg.det(B)
print(f"Determinant of the matrix is: {determinant:.2f}")

# Calculate the inverse if the determinant is non-zero
if determinant != 0:
    inverse = np.linalg.inv(B)
    print("\nInverse of the matrix:")
    print(inverse)
else:
    print("The matrix is singular and does not have an inverse.")


Determinant of the matrix is: -0.00

Inverse of the matrix:
[[-9.00719925e+15  2.00159983e+15  5.00399959e+15]
 [ 9.00719925e+15 -2.00159983e+15 -5.00399959e+15]
 [-9.00719925e+15  2.00159983e+15  5.00399959e+15]]


## Properties and Applications of the Normal Distribution
Calculate the probability of a random variable 
𝑋
X being less than a given value 
𝑥
x in a normal distribution with a mean of 100 and a standard deviation of 15.

In [4]:
import scipy.stats as stats

# Given parameters
mean = 100
std_dev = 15
x_value = 110

# Calculate the cumulative probability
probability = stats.norm.cdf(x_value, loc=mean, scale=std_dev)

print(f"The probability that X is less than {x_value} is: {probability:.4f}")


The probability that X is less than 110 is: 0.7475
